# Generated by Django 4.0.6 on 2022-08-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=40)),
                ('blog_description', models.CharField(max_length=200)),
                ('blog_date', models.DateField(auto_now_add=True, null=True)),
                ('blog_author', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Celphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celphone_name', models.CharField(max_length=40)),
                ('celphone_price', models.FloatField()),
                ('celphone_brand', models.CharField(max_length=40)),
                ('celphone_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('user_email', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=40)),
                ('user_role', models.CharField(max_length=40)),
            ],
        ),
    ]
